apiVersion: v1
kind: PersistentVolume
metadata:
  name: resource-mongo-pv
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/resource-mongo
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resource-mongo-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: resource-mongo-pv

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-mongo
  template:
    metadata:
      labels:
        app: resource-mongo
    spec:
      containers:
        - name: resource-mongo
          image: mongo:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: resource-mongo-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: resource-mongo-srv
spec:
  type: ClusterIP
  selector:
    app: resource-mongo
  ports:
    - name: resource-mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
