apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: converter
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
        - name: converter
          image: dialloabdourahman/converter-converter:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITMQ_URL
              value: "amqp://user:password@rabbitmq-srv:5672"
            - name: ACCESS_TOKEN_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-converter-secret
                  key: ACCESS_TOKEN_JWT_KEY
            - name: AWS_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: aws-converter-secret
                  key: AWS_BUCKET_NAME
            - name: AWS_BUCKET_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-converter-secret
                  key: AWS_BUCKET_REGION
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-converter-secret
                  key: AWS_ACCESS_KEY
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-converter-secret
                  key: AWS_SECRET_KEY
